name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test app locally
      run: |
        # Basic syntax check
        python -c "import app; print('App imports successfully')"
    
    - name: Deploy to Hugging Face Spaces
      if: github.ref == 'refs/heads/main'
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
      run: |
        # Clone HF Space
        git clone https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME hf_space
        
        # Copy files to HF Space
        cp -r . hf_space/
        cd hf_space
        
        # Configure git
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        # Commit and push
        git add .
        git commit -m "Auto-deploy from GitHub Actions" || exit 0
        git push