name: Deploy to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true  # ✅ Checkout cả Git LFS

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://oauth2:${HF_TOKEN}@huggingface.co/spaces/F4t/X-ray-Bone-Fracture-Detector hf_space
          rsync -av --exclude '.git' ./ hf_space/
          cd hf_space
          git lfs track "*.pt"    # ✅ Đảm bảo track file .pt
          git add .gitattributes
          git add .
          git commit -m "Auto-deploy from GitHub Actions" || echo "No changes to commit"
          git push
